# Generated by Django 3.2.10 on 2022-02-19 11:36

import NeatellerApp.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 973560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 973560), null=True)),
            ],
            options={
                'verbose_name': 'Unit Type',
                'verbose_name_plural': 'Unit Types',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('country', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 974560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 974560), null=True)),
            ],
            options={
                'verbose_name': 'Local City',
                'verbose_name_plural': 'Local Cities',
            },
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='123456', length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('countrycode', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Contacted', 'Contacted')], default='NA', max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 969560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 969560), null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('slug', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 974561), null=True)),
                ('updated_at', models.DateField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 974561), null=True)),
            ],
            options={
                'verbose_name': 'Country List',
                'verbose_name_plural': 'Country Lists',
            },
        ),
        migrations.CreateModel(
            name='PopupBuilders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('type', models.CharField(blank=True, max_length=191, null=True)),
                ('title', models.CharField(blank=True, max_length=191, null=True)),
                ('only_image', models.CharField(blank=True, max_length=191, null=True)),
                ('background_image', models.CharField(blank=True, max_length=191, null=True)),
                ('offer_time_end', models.CharField(blank=True, max_length=191, null=True)),
                ('button_text', models.CharField(blank=True, max_length=191, null=True)),
                ('button_link', models.CharField(blank=True, max_length=191, null=True)),
                ('btn_status', models.CharField(blank=True, max_length=191, null=True)),
                ('lang', models.CharField(blank=True, max_length=191, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 969560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 969560), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=191)),
                ('discount', models.CharField(blank=True, max_length=191, null=True)),
                ('discount_type', models.CharField(blank=True, max_length=191, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 970560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 970560), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=191, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=191, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=191, null=True)),
                ('payment_track', models.CharField(blank=True, max_length=191, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=191, null=True)),
                ('user_id', models.CharField(blank=True, max_length=191, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=191, null=True)),
                ('coupon_discount', models.CharField(blank=True, max_length=191, null=True)),
                ('shipping_cost', models.CharField(blank=True, max_length=191, null=True)),
                ('product_shippings_id', models.CharField(blank=True, max_length=191, null=True)),
                ('total', models.CharField(blank=True, max_length=191, null=True)),
                ('billing_name', models.TextField(blank=True, null=True)),
                ('billing_email', models.TextField(blank=True, null=True)),
                ('billing_phone', models.TextField(blank=True, null=True)),
                ('billing_country', models.TextField(blank=True, null=True)),
                ('billing_street_address', models.TextField(blank=True, null=True)),
                ('billing_town', models.TextField(blank=True, null=True)),
                ('billing_district', models.TextField(blank=True, null=True)),
                ('different_shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_name', models.TextField(blank=True, null=True)),
                ('shipping_email', models.TextField(blank=True, null=True)),
                ('shipping_phone', models.TextField(blank=True, null=True)),
                ('shipping_country', models.TextField(blank=True, null=True)),
                ('shipping_street_address', models.TextField(blank=True, null=True)),
                ('shipping_town', models.TextField(blank=True, null=True)),
                ('shipping_district', models.TextField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=191, null=True)),
                ('cart_items', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 971560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 971560), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('product_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 971560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 971560), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('page', models.CharField(max_length=500, unique=True)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=NeatellerApp.models.servicefilename)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 972560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 972560), null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 972560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 972560), null=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(default='', max_length=150)),
                ('first_name', models.CharField(blank=True, default='', max_length=250)),
                ('last_name', models.CharField(blank=True, default='', max_length=250)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 968560))),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 968560))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sec_label', models.CharField(default=None, max_length=500, null=True)),
                ('base_price', models.CharField(default=None, max_length=500, null=True)),
                ('sec_divs', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 975560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 975560), null=True)),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Service Section',
                'verbose_name_plural': 'Service Sections',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.servicecategories'),
        ),
        migrations.CreateModel(
            name='RandoChoice_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceques', models.CharField(default=None, max_length=500)),
                ('serName', models.CharField(max_length=500)),
                ('serNumber', models.CharField(default=None, max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 977560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 977560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Random Choice',
                'verbose_name_plural': 'Random Choices',
            },
        ),
        migrations.CreateModel(
            name='Offer_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offquestion', models.CharField(default=None, max_length=800, null=True)),
                ('offserName', models.CharField(max_length=500)),
                ('offserperc', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 978560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 978560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Offered Service',
                'verbose_name_plural': 'Offered Services',
            },
        ),
        migrations.CreateModel(
            name='LocalAddre_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locquesName', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 979561), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 979561), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'LocalAddress Service',
                'verbose_name_plural': 'LocalAddress Services',
            },
        ),
        migrations.CreateModel(
            name='InternAddre_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interquesName', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 980561), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 980561), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'International Address Service',
                'verbose_name_plural': 'International Address Services',
            },
        ),
        migrations.CreateModel(
            name='Description_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('placeholder', models.CharField(max_length=500)),
                ('required', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 976560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 976560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Description Service',
                'verbose_name_plural': 'Description Services',
            },
        ),
        migrations.CreateModel(
            name='Date_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dquestion', models.CharField(max_length=800)),
                ('drequired', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 981561), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 981561), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Date Service',
                'verbose_name_plural': 'Date Service',
            },
        ),
        migrations.CreateModel(
            name='Choice_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choicequestion', models.CharField(default=None, max_length=800, null=True)),
                ('choiserName', models.CharField(max_length=500)),
                ('choiserPrice', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 978560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 978560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Choice Service',
                'verbose_name_plural': 'Choice Services',
            },
        ),
        migrations.CreateModel(
            name='Apartment_Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 973560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 973560), null=True)),
                ('type', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.apartment_unit')),
            ],
            options={
                'verbose_name': 'Sub Unit',
                'verbose_name_plural': 'Sub Units',
            },
        ),
        migrations.CreateModel(
            name='Advance_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servlist', models.CharField(max_length=800)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 980561), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 980561), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Advance Service',
                'verbose_name_plural': 'Advance Service',
            },
        ),
        migrations.CreateModel(
            name='AddOn_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serName', models.CharField(max_length=500)),
                ('serPrice', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 977560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 977560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'Add-On Service',
                'verbose_name_plural': 'Add-On Services',
            },
        ),
        migrations.CreateModel(
            name='About_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('points', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 975560), null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 17, 6, 31, 975560), null=True)),
                ('sectionName', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service_section')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeatellerApp.service')),
            ],
            options={
                'verbose_name': 'About Service',
                'verbose_name_plural': 'About Services',
            },
        ),
    ]
