# Generated by Django 3.2.10 on 2022-02-19 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeatellerApp', '0002_auto_20220219_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 612334), null=True),
        ),
        migrations.AlterField(
            model_name='about_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 612334), null=True),
        ),
        migrations.AlterField(
            model_name='addon_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 613334), null=True),
        ),
        migrations.AlterField(
            model_name='addon_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 613334), null=True),
        ),
        migrations.AlterField(
            model_name='advance_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 617334), null=True),
        ),
        migrations.AlterField(
            model_name='advance_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 617334), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_categorie',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 610334), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_categorie',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 610334), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_unit',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 610334), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_unit',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 610334), null=True),
        ),
        migrations.AlterField(
            model_name='choice_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 615334), null=True),
        ),
        migrations.AlterField(
            model_name='choice_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 615334), null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 611334), null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 611334), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 606334), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 606334), null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 611334), null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 611334), null=True),
        ),
        migrations.AlterField(
            model_name='date_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 618334), null=True),
        ),
        migrations.AlterField(
            model_name='date_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 618334), null=True),
        ),
        migrations.AlterField(
            model_name='description_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 613334), null=True),
        ),
        migrations.AlterField(
            model_name='description_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 613334), null=True),
        ),
        migrations.AlterField(
            model_name='internaddre_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 617334), null=True),
        ),
        migrations.AlterField(
            model_name='internaddre_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 617334), null=True),
        ),
        migrations.AlterField(
            model_name='localaddre_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 616334), null=True),
        ),
        migrations.AlterField(
            model_name='localaddre_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 616334), null=True),
        ),
        migrations.AlterField(
            model_name='offer_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 614334), null=True),
        ),
        migrations.AlterField(
            model_name='offer_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 614334), null=True),
        ),
        migrations.AlterField(
            model_name='popupbuilders',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 606334), null=True),
        ),
        migrations.AlterField(
            model_name='popupbuilders',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 606334), null=True),
        ),
        migrations.AlterField(
            model_name='productcoupons',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 607334), null=True),
        ),
        migrations.AlterField(
            model_name='productcoupons',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 607334), null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 608334), null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 608334), null=True),
        ),
        migrations.AlterField(
            model_name='productratings',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 608334), null=True),
        ),
        migrations.AlterField(
            model_name='productratings',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 608334), null=True),
        ),
        migrations.AlterField(
            model_name='randochoice_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 614334), null=True),
        ),
        migrations.AlterField(
            model_name='randochoice_service',
            name='serNumber',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='randochoice_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 614334), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 609334), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 609334), null=True),
        ),
        migrations.AlterField(
            model_name='service_section',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 612334), null=True),
        ),
        migrations.AlterField(
            model_name='service_section',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 612334), null=True),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 609334), null=True),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 609334), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 605334)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 18, 15, 31, 605334)),
        ),
    ]
