# Generated by Django 3.2.10 on 2022-04-15 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeatellerApp', '0057_auto_20220415_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 463023), null=True),
        ),
        migrations.AlterField(
            model_name='about_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 463023), null=True),
        ),
        migrations.AlterField(
            model_name='addon_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 464023), null=True),
        ),
        migrations.AlterField(
            model_name='addon_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 464023), null=True),
        ),
        migrations.AlterField(
            model_name='advance_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 469024), null=True),
        ),
        migrations.AlterField(
            model_name='advance_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 469024), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_categorie',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 461023), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_categorie',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 461023), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_unit',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 461023), null=True),
        ),
        migrations.AlterField(
            model_name='apartment_unit',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 461023), null=True),
        ),
        migrations.AlterField(
            model_name='choice_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 466023), null=True),
        ),
        migrations.AlterField(
            model_name='choice_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 466023), null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 462023), null=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 462023), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 457023), null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 457023), null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 462024), null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='updated_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 462024), null=True),
        ),
        migrations.AlterField(
            model_name='date_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 470024), null=True),
        ),
        migrations.AlterField(
            model_name='date_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 470024), null=True),
        ),
        migrations.AlterField(
            model_name='description_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 464023), null=True),
        ),
        migrations.AlterField(
            model_name='description_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 464023), null=True),
        ),
        migrations.AlterField(
            model_name='internaddre_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 468024), null=True),
        ),
        migrations.AlterField(
            model_name='internaddre_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 468024), null=True),
        ),
        migrations.AlterField(
            model_name='localaddre_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 468024), null=True),
        ),
        migrations.AlterField(
            model_name='localaddre_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 468024), null=True),
        ),
        migrations.AlterField(
            model_name='material_perhour',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 467024), null=True),
        ),
        migrations.AlterField(
            model_name='material_perhour',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 467024), null=True),
        ),
        migrations.AlterField(
            model_name='offer_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 466023), null=True),
        ),
        migrations.AlterField(
            model_name='offer_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 466023), null=True),
        ),
        migrations.AlterField(
            model_name='popupbuilders',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 458023), null=True),
        ),
        migrations.AlterField(
            model_name='popupbuilders',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 458023), null=True),
        ),
        migrations.AlterField(
            model_name='productcoupons',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 458023), null=True),
        ),
        migrations.AlterField(
            model_name='productcoupons',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 458023), null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 459023), null=True),
        ),
        migrations.AlterField(
            model_name='productorders',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 459023), null=True),
        ),
        migrations.AlterField(
            model_name='productratings',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 459023), null=True),
        ),
        migrations.AlterField(
            model_name='productratings',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 460023), null=True),
        ),
        migrations.AlterField(
            model_name='randochoice_service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 465023), null=True),
        ),
        migrations.AlterField(
            model_name='randochoice_service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 465023), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 460023), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 460023), null=True),
        ),
        migrations.AlterField(
            model_name='service_section',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 463023), null=True),
        ),
        migrations.AlterField(
            model_name='service_section',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 463023), null=True),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 460023), null=True),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 460023), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 456023)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 456023)),
        ),
        migrations.AlterField(
            model_name='user_booking_details',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 472024), null=True),
        ),
        migrations.AlterField(
            model_name='user_booking_details',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 472024), null=True),
        ),
        migrations.AlterField(
            model_name='user_payment_transaction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 471024), null=True),
        ),
        migrations.AlterField(
            model_name='user_payment_transaction',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 471024), null=True),
        ),
        migrations.AlterField(
            model_name='usersaddress',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 470024), null=True),
        ),
        migrations.AlterField(
            model_name='usersaddress',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 15, 12, 37, 56, 470024), null=True),
        ),
    ]
